"""empty message

Revision ID: 191fab20ceed
Revises: 6a5dc5e9fc09
Create Date: 2022-05-31 08:42:19.340602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191fab20ceed'
down_revision = '6a5dc5e9fc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'past_shows_count')
    op.drop_column('venues', 'upcoming_shows_count')
    # ### end Alembic commands ###
